WIP

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -56,53 +56,53 @@ IMAGE_MAGICK_VERSION="7.1.1-45"
 CACHE_FILE="$CACHE_DIR/imagemagick-$IMAGE_MAGICK_VERSION.tar.gz"
 VENDOR_DIR="$BUILD_DIR/vendor"
 mkdir -p $VENDOR_DIR
+INSTALL_DIR="$VENDOR_DIR/imagemagick"
+mkdir -p $INSTALL_DIR
 
-# if [ ! -f $CACHE_FILE ]; then
-#   INSTALL_DIR="$VENDOR_DIR/imagemagick"
-#   mkdir -p $INSTALL_DIR
-#   # install imagemagick
-#   IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.xz"
-#   IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
-#   # SSL cert used on imagemagick not recognized by heroku.
-#   IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
-#
-#   echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
-#   wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
-#
-#   echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
-#   if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
-#     echo "Error: Unable to download ImageMagick" | indent
-#     ls $BUILD_DIR | indent
-#     exit 1;
-#   fi
-#   tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
-#
-#   echo "-----> Building ImageMagick"
-#   cd $IMAGE_MAGICK_DIR
-#   export CPPFLAGS="-I$INSTALL_DIR/include"
-#   export LDFLAGS="-L$INSTALL_DIR/lib"
-#   ./configure --prefix=$INSTALL_DIR --without-gvc
-#   make && make install
-#   cd ..
-#   rm -rf $IMAGE_MAGICK_DIR
-#
-#   # cache for future deploys
-#   echo "-----> Caching ImageMagick installation"
-#   cd $VENDOR_DIR
-#   REL_INSTALL_DIR="imagemagick"
-#   tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
-#   mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
-# else
-#   # cache exists, extract it
-#   echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
-#   # tar xzf $CACHE_FILE -C "$BUILD_DIR/vendor/imagemagick"
-#   tar xzf $CACHE_FILE -C $VENDOR_DIR
-# fi
+if [ ! -f $CACHE_FILE ]; then
+  # install imagemagick
+  IMAGE_MAGICK_FILE="ImageMagick-$IMAGE_MAGICK_VERSION.tar.xz"
+  IMAGE_MAGICK_DIR="ImageMagick-$IMAGE_MAGICK_VERSION"
+  # SSL cert used on imagemagick not recognized by heroku.
+  IMAGE_MAGICK_URL="http://www.imagemagick.org/download/releases/$IMAGE_MAGICK_FILE"
+
+  echo "-----> Downloading ImageMagick from $IMAGE_MAGICK_URL"
+  wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
+
+  echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
+  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+    echo "Error: Unable to download ImageMagick" | indent
+    ls $BUILD_DIR | indent
+    exit 1;
+  fi
+  tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
+
+  echo "-----> Building ImageMagick"
+  cd $IMAGE_MAGICK_DIR
+  export CPPFLAGS="-I$INSTALL_DIR/include"
+  export LDFLAGS="-L$INSTALL_DIR/lib"
+  ./configure --prefix=$INSTALL_DIR --without-gvc
+  make && make install
+  cd ..
+  rm -rf $IMAGE_MAGICK_DIR
+
+  # cache for future deploys
+  echo "-----> Caching ImageMagick installation"
+  cd $VENDOR_DIR
+  REL_INSTALL_DIR="imagemagick"
+  tar czf $REL_INSTALL_DIR.tar.gz $REL_INSTALL_DIR
+  mv $REL_INSTALL_DIR.tar.gz $CACHE_FILE
+else
+  # cache exists, extract it
+  echo "-----> Extracting ImageMagick $CACHE_FILE => $VENDOR_DIR"
+  # tar xzf $CACHE_FILE -C "$BUILD_DIR/vendor/imagemagick"
+  # tar xzf $CACHE_FILE -C $VENDOR_DIR
+fi
 
 echo "Vendoring binaries" | arrow
 
 if [[ "$STACK" == "heroku-24" ]]; then
-  # echo "Vendoring on heroku-24"
+  echo "Vendoring on heroku-24"
   # ls $CACHE_DIR
   # echo "------------------"
   # ls $VENDOR_DIR
@@ -111,9 +111,9 @@ if [[ "$STACK" == "heroku-24" ]]; then
   # echo "------------------"
   # echo "CACHE_FILE: $CACHE_FILE"
   # echo "------------------"
-  vendor "${ROOT_DIR}/build/imagemagick-heroku-24.tar.gz" "$BUILD_DIR/vendor/imagemagick"
+  # vendor "${ROOT_DIR}/build/imagemagick-heroku-24.tar.gz" "$BUILD_DIR/vendor/imagemagick"
   # echo "------------------"
-  # vendor $CACHE_FILE "$BUILD_DIR/vendor/imagemagick"
+  vendor $CACHE_FILE "$BUILD_DIR/vendor/imagemagick"
 elif [[ "$STACK" == "heroku-22" ]]; then
   echo "Vendoring on heroku-22"
   vendor "${ROOT_DIR}/build/imagemagick-heroku-22.tar.gz" "$BUILD_DIR/vendor/imagemagick"
